pipeline {
    agent any

    environment {
        DOCKER_IMAGE = 'app'
        DOCKER_REGISTRY = 'haquocviet'
    }

    stages {
        stage('Build') {
            steps {
                script {
                    docker.withServer('tcp://docker:2375') {
                        // Đảm bảo Docker daemon có thể được truy cập bằng cách sử dụng docker:2375
                        docker.build("${DOCKER_IMAGE}:${env.BUILD_NUMBER}", "./Backend/project")
                    }
                }
            }
        }

        stage('Push') {
            steps {
                script {
                    docker.withRegistry('https://index.docker.io/v1/', 'haquocviet') {
                        docker.image("${DOCKER_IMAGE}:${env.BUILD_NUMBER}").push()
                    }
                }
            }
        }

        stage('Deploy') {
            steps {
                script {
                    docker.withServer('tcp://docker:2375') {
                        sh '''
                            docker-compose down || true
                            docker-compose up -d
                        '''
                    }
                }
            }
        }
    }

    post {
        success {
            echo 'Build successfully!'
        }
        failure {
            echo 'Build failed!'
        }
        always {
            script {
                sh "docker rm -f app || true"
                sh "docker rmi ${DOCKER_REGISTRY}/${DOCKER_IMAGE}:${env.BUILD_NUMBER} || true"
            }
        }
    }
}
