pipeline {
    agent any

    stages {
        stage('Build') {
            steps {
                dir('project') {
                    sh 'chmod +x mvnw'
                    sh './mvnw clean install'
                }
            }
        }
        stage('Build Docker Image') {
            steps {
                dir('project') {
                    script {
                        sh "docker build -t ${DOCKER_IMAGE}:${DOCKER_TAG} ."
                    }
                }
            }
        }
        stage('Deploy Docker Container') {
            steps {
                script {
                    // Stop và remove container cũ (nếu có) trước khi chạy container mới
                    sh '''
                        docker stop iot_app || true
                        docker rm iot_app || true
                        docker run -d -p 9999:9999 --name iot_app iot_app
                    '''
                }
            }
        }
    }
}
